apiVersion: v1
kind: ConfigMap
metadata:
  name: zq2-stake-frontend
  namespace: zq2-stake-stg-prototestnet
  labels:
    app.kubernetes.io/name: zq2-stake-frontend
data:
  ZQ2_STAKING_CHAIN_ID: "33103"
  ZQ2_STAKING_APP_URL: "https://stake.zq2-prototestnet.zilliqa.com"
  ZQ2_PREVIEW_SECRET_HASH: "N/A"
