apiVersion: v1
kind: ConfigMap
metadata:
  name: zq2-stake-frontend
  namespace: zq2-stake
  labels:
    app.kubernetes.io/name: zq2-stake-frontend
data:
  ZQ2_STAKING_CHAIN_ID: "33469"
  ZQ2_STAKING_APP_URL: "http://localhost:3000"
  ZQ2_PREVIEW_SECRET_HASH: "N/A"
