apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zq2-stake-prd-mainnet

resources:
  - ../../base
  - backendpolicy.yaml
  - httproute.yaml

patches:
  - target:
      kind: ConfigMap
      name: zq2-stake-frontend
    path: configmap.yaml
  - target:
      kind: Secret
      name: zq2-stake-frontend
    path: secrets.yaml
