apiVersion: v1
kind: ConfigMap
metadata:
  name: zq2-stake-frontend
  namespace: zq2-stake-prd-mainnet-preview
  labels:
    app.kubernetes.io/name: zq2-stake-frontend
data:
  ZQ2_STAKING_CHAIN_ID: "32770"
  ZQ2_STAKING_APP_URL: "https://stake-preview.zilliqa.com"
